travis:
  secure:
    BINSTAR_TOKEN: O6AhAydmjnu5WweylARZMGRtXoRf4j7TcFhgEqkGERCTiZPMoShnAjVRDUHbpwJfYLyYazn7/EPfhG1D5kn22BvzRpBcFhastRW0Imm4bs3wZzPMgHbSJ8Bly+KMVEfCqGut2voqhi5hEhaUGOxQlcwatU/+u+mc+PUjshiB09xMtzLHsGuvAhqgefrdr1IIv2zkGJL5XV42usMeJpMx/VyK3tvHnQvoprkMYvIFxqW7yOPvNziE2Rbc/QA8ioarLihQsYNf/1rEtXED219cF1eX0Qo6zAIkpp1LlC1wbMKDTOJPhv2AevxZdn00ryEg3wx1J3pN7SXj1dOYQ4S4zwyBGSIxLTpEII/sRvD4UJGmrN6zST/YvYzcGEh8sCQV4vNleBVZpISrulg1aWzdsBfBrhKGYsjFqDvjRQL+idR0QNuESzdY99syhPLQ1jyBbUNGLRFvigDa8l9wu186oelHTNlqAG3QwoP/6qRrDNhjeubZ2woNBdkwyoJi68lqkCTKy7O/oYzb9L0g/3snAwunyJHN5bv/BBH1axRuVH6E+sRYLYiELs6rGUGOVvKwwSMj9WyheQ/jyYKffCC+PRjJ9o464x/MwhkG8z+dmDHoHsWBEf8YfUzNIBriPOwzll5R8u9VG/kIBSjoIXn3xGjMhy3TbCwOnr7IudBFAH0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
